//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Core.Common.DataModel.Market;
namespace Market.Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VivosEntities : DbContext
    {
        public VivosEntities()
            : base("name=VivosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssetCommand> AssetCommands { get; set; }
        public virtual DbSet<AssetDefault> AssetDefaults { get; set; }
        public virtual DbSet<AssetGroup> AssetGroups { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<AssetThumbnail> AssetThumbnails { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<Safe> Safes { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
    }
}
