//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivoosVR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VivosEntities : DbContext
    {
        public VivosEntities()
            : base("name=VivosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<ConsumerProperty> ConsumerProperties { get; set; }
        public virtual DbSet<Consumer> Consumers { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleToUserMap> RoleToUserMaps { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ConsumerPropertyType> ConsumerPropertyTypes { get; set; }
        public virtual DbSet<AssetCommand> AssetCommands { get; set; }
        public virtual DbSet<AssetDefault> AssetDefaults { get; set; }
        public virtual DbSet<AssetGroup> AssetGroups { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<AssetThumbnail> AssetThumbnails { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<Safe> Safes { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
    }
}
