//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivoosVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleToUserMap
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public string RoleCode { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool Available { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
