// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AssetWithImage
    {
        /// <summary>
        /// Initializes a new instance of the AssetWithImage class.
        /// </summary>
        public AssetWithImage() { }

        /// <summary>
        /// Initializes a new instance of the AssetWithImage class.
        /// </summary>
        public AssetWithImage(Guid? id = default(Guid?), string name = default(string), string description = default(string), string image = default(string))
        {
            Id = id;
            Name = name;
            Description = description;
            Image = image;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Image")]
        public string Image { get; set; }

    }
}
