// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Consumer
    {
        /// <summary>
        /// Initializes a new instance of the Consumer class.
        /// </summary>
        public Consumer() { }

        /// <summary>
        /// Initializes a new instance of the Consumer class.
        /// </summary>
        public Consumer(Guid? id = default(Guid?), string code = default(string), string description = default(string), string email = default(string), DateTime? entryDate = default(DateTime?), string windowsCode = default(string), Branch branch = default(Branch), Company company = default(Company), IList<ConsumerProperty> consumerProperties = default(IList<ConsumerProperty>), Group group = default(Group), User user = default(User))
        {
            Id = id;
            Code = code;
            Description = description;
            Email = email;
            EntryDate = entryDate;
            WindowsCode = windowsCode;
            Branch = branch;
            Company = company;
            ConsumerProperties = consumerProperties;
            Group = group;
            User = user;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EntryDate")]
        public DateTime? EntryDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WindowsCode")]
        public string WindowsCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Branch")]
        public Branch Branch { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Company")]
        public Company Company { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ConsumerProperties")]
        public IList<ConsumerProperty> ConsumerProperties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Group")]
        public Group Group { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "User")]
        public User User { get; set; }

    }
}
