// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetAllAssetsWithImagesResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetAllAssetsWithImagesResponse
        /// class.
        /// </summary>
        public GetAllAssetsWithImagesResponse() { }

        /// <summary>
        /// Initializes a new instance of the GetAllAssetsWithImagesResponse
        /// class.
        /// </summary>
        public GetAllAssetsWithImagesResponse(IList<AssetWithImage> assets = default(IList<AssetWithImage>), string message = default(string), bool? hasError = default(bool?))
        {
            Assets = assets;
            Message = message;
            HasError = hasError;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Assets")]
        public IList<AssetWithImage> Assets { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HasError")]
        public bool? HasError { get; set; }

    }
}
