// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class IdentityUserClaim
    {
        /// <summary>
        /// Initializes a new instance of the IdentityUserClaim class.
        /// </summary>
        public IdentityUserClaim() { }

        /// <summary>
        /// Initializes a new instance of the IdentityUserClaim class.
        /// </summary>
        public IdentityUserClaim(int? id = default(int?), string userId = default(string), string claimType = default(string), string claimValue = default(string))
        {
            Id = id;
            UserId = userId;
            ClaimType = claimType;
            ClaimValue = claimValue;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClaimType")]
        public string ClaimType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClaimValue")]
        public string ClaimValue { get; set; }

    }
}
