// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class User
    {
        /// <summary>
        /// Initializes a new instance of the User class.
        /// </summary>
        public User() { }

        /// <summary>
        /// Initializes a new instance of the User class.
        /// </summary>
        public User(Guid? id = default(Guid?), Guid? groupId = default(Guid?), DateTime? expireDate = default(DateTime?), byte[] picture = default(byte[]), string password = default(string), bool? available = default(bool?), Consumer consumer = default(Consumer), Group group = default(Group), IList<RoleToUserMap> roleToUserMaps = default(IList<RoleToUserMap>))
        {
            Id = id;
            GroupId = groupId;
            ExpireDate = expireDate;
            Picture = picture;
            Password = password;
            Available = available;
            Consumer = consumer;
            Group = group;
            RoleToUserMaps = roleToUserMaps;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GroupId")]
        public Guid? GroupId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExpireDate")]
        public DateTime? ExpireDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Picture")]
        public byte[] Picture { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Available")]
        public bool? Available { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Consumer")]
        public Consumer Consumer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Group")]
        public Group Group { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RoleToUserMaps")]
        public IList<RoleToUserMap> RoleToUserMaps { get; set; }

    }
}
