// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BaseListRequest
    {
        /// <summary>
        /// Initializes a new instance of the BaseListRequest class.
        /// </summary>
        public BaseListRequest() { }

        /// <summary>
        /// Initializes a new instance of the BaseListRequest class.
        /// </summary>
        public BaseListRequest(int? current = default(int?), int? rowCount = default(int?), string searchPhrase = default(string), SortData sortItem = default(SortData))
        {
            Current = current;
            RowCount = rowCount;
            SearchPhrase = searchPhrase;
            SortItem = sortItem;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Current")]
        public int? Current { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RowCount")]
        public int? RowCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SearchPhrase")]
        public string SearchPhrase { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SortItem")]
        public SortData SortItem { get; set; }

    }
}
