// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Branch
    {
        /// <summary>
        /// Initializes a new instance of the Branch class.
        /// </summary>
        public Branch() { }

        /// <summary>
        /// Initializes a new instance of the Branch class.
        /// </summary>
        public Branch(Guid? id = default(Guid?), Guid? companyId = default(Guid?), Company company = default(Company), Consumer consumer = default(Consumer), IList<Group> groups = default(IList<Group>))
        {
            Id = id;
            CompanyId = companyId;
            Company = company;
            Consumer = consumer;
            Groups = groups;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CompanyId")]
        public Guid? CompanyId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Company")]
        public Company Company { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Consumer")]
        public Consumer Consumer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Groups")]
        public IList<Group> Groups { get; set; }

    }
}
