// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Company
    {
        /// <summary>
        /// Initializes a new instance of the Company class.
        /// </summary>
        public Company() { }

        /// <summary>
        /// Initializes a new instance of the Company class.
        /// </summary>
        public Company(Guid? id = default(Guid?), byte[] logo = default(byte[]), IList<Branch> branches = default(IList<Branch>), Consumer consumer = default(Consumer))
        {
            Id = id;
            Logo = logo;
            Branches = branches;
            Consumer = consumer;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Logo")]
        public byte[] Logo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Branches")]
        public IList<Branch> Branches { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Consumer")]
        public Consumer Consumer { get; set; }

    }
}
