// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ConsumerPropertyType
    {
        /// <summary>
        /// Initializes a new instance of the ConsumerPropertyType class.
        /// </summary>
        public ConsumerPropertyType() { }

        /// <summary>
        /// Initializes a new instance of the ConsumerPropertyType class.
        /// </summary>
        public ConsumerPropertyType(int? no = default(int?), string name = default(string), IList<ConsumerProperty> consumerProperties = default(IList<ConsumerProperty>))
        {
            No = no;
            Name = name;
            ConsumerProperties = consumerProperties;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "No")]
        public int? No { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ConsumerProperties")]
        public IList<ConsumerProperty> ConsumerProperties { get; set; }

    }
}
