// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Group
    {
        /// <summary>
        /// Initializes a new instance of the Group class.
        /// </summary>
        public Group() { }

        /// <summary>
        /// Initializes a new instance of the Group class.
        /// </summary>
        public Group(Guid? id = default(Guid?), Guid? branchId = default(Guid?), Branch branch = default(Branch), Consumer consumer = default(Consumer), IList<User> users = default(IList<User>))
        {
            Id = id;
            BranchId = branchId;
            Branch = branch;
            Consumer = consumer;
            Users = users;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BranchId")]
        public Guid? BranchId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Branch")]
        public Branch Branch { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Consumer")]
        public Consumer Consumer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Users")]
        public IList<User> Users { get; set; }

    }
}
