// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class IdentityUserRole
    {
        /// <summary>
        /// Initializes a new instance of the IdentityUserRole class.
        /// </summary>
        public IdentityUserRole() { }

        /// <summary>
        /// Initializes a new instance of the IdentityUserRole class.
        /// </summary>
        public IdentityUserRole(string userId = default(string), string roleId = default(string))
        {
            UserId = userId;
            RoleId = roleId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RoleId")]
        public string RoleId { get; set; }

    }
}
