// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class RoleToUserMap
    {
        /// <summary>
        /// Initializes a new instance of the RoleToUserMap class.
        /// </summary>
        public RoleToUserMap() { }

        /// <summary>
        /// Initializes a new instance of the RoleToUserMap class.
        /// </summary>
        public RoleToUserMap(Guid? id = default(Guid?), Guid? userId = default(Guid?), string roleCode = default(string), DateTime? validUntil = default(DateTime?), DateTime? entryDate = default(DateTime?), bool? available = default(bool?), Role role = default(Role), User user = default(User))
        {
            Id = id;
            UserId = userId;
            RoleCode = roleCode;
            ValidUntil = validUntil;
            EntryDate = entryDate;
            Available = available;
            Role = role;
            User = user;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public Guid? UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RoleCode")]
        public string RoleCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ValidUntil")]
        public DateTime? ValidUntil { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EntryDate")]
        public DateTime? EntryDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Available")]
        public bool? Available { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Role")]
        public Role Role { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "User")]
        public User User { get; set; }

    }
}
