// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ConsoleApplication1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SortData
    {
        /// <summary>
        /// Initializes a new instance of the SortData class.
        /// </summary>
        public SortData() { }

        /// <summary>
        /// Initializes a new instance of the SortData class.
        /// </summary>
        public SortData(string field = default(string), string type = default(string), object sortFunc = default(object))
        {
            Field = field;
            Type = type;
            SortFunc = sortFunc;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Field")]
        public string Field { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SortFunc")]
        public object SortFunc { get; set; }

    }
}
