//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Core.Common.DataModel.Core;

namespace Core.Server.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoreEntities : DbContext
    {
        public CoreEntities()
            : base("name=CoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<ConsumerProperty> ConsumerProperties { get; set; }
        public virtual DbSet<Consumer> Consumers { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleToUserMap> RoleToUserMaps { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ConsumerPropertyType> ConsumerPropertyTypes { get; set; }
    }
}
