//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Common.DataModel.Core
{
    
    using System.Runtime.Serialization;
    
    using System;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.RoleToUserMaps = new HashSet<RoleToUserMap>();
        }
    
    	[DataMember]
        public System.Guid Id { get; set; }
    	[DataMember]
        public System.Guid GroupId { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> ExpireDate { get; set; }
    	[DataMember]
        public byte[] Picture { get; set; }
    	[DataMember]
        public string Password { get; set; }
    	[DataMember]
        public bool Available { get; set; }
    
    	[DataMember]
        public virtual Consumer Consumer { get; set; }
    	[DataMember]
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<RoleToUserMap> RoleToUserMaps { get; set; }
    }
}
