//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Common.DataModel.Market
{
    
    using System.Runtime.Serialization;
    
    
    using System;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    public partial class AssetThumbnail
    {
    	[DataMember]
        public System.Guid AssetId { get; set; }
    	[DataMember]
        public byte[] Thumbnail { get; set; }
    
    	[DataMember]
        public virtual Asset Asset { get; set; }
    
    }
}
