//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Common.DataModel.Market
{
    
    using System.Runtime.Serialization;
    
    
    using System;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.AssetCommands = new HashSet<AssetCommand>();
            this.AssetDefaults = new HashSet<AssetDefault>();
            this.Safes = new HashSet<Safe>();
            this.Sessions = new HashSet<Session>();
        }
    
    	[DataMember]
        public System.Guid Id { get; set; }
    	[DataMember]
        public System.Guid GroupId { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public bool Available { get; set; }
    	[DataMember]
        public string Url { get; set; }
    	[DataMember]
        public string Exe { get; set; }
    	[DataMember]
        public System.DateTime EntryDate { get; set; }
    	[DataMember]
        public System.DateTime ModifyDate { get; set; }
    	[DataMember]
        public System.Guid UpdateStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<AssetCommand> AssetCommands { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<AssetDefault> AssetDefaults { get; set; }
    
    	[DataMember]
        public virtual AssetGroup AssetGroup { get; set; }
    
    	[DataMember]
        public virtual AssetThumbnail AssetThumbnail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<Safe> Safes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<Session> Sessions { get; set; }
    
    }
}
