//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivoosVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public System.Guid Id { get; set; }
        public System.DateTime SessionDateTime { get; set; }
        public string Notes { get; set; }
        public string SensorData { get; set; }
        public System.Guid AssetId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
