//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Common.DataModel.Core
{
    
    using System.Runtime.Serialization;
    
    using System;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    public partial class ConsumerProperty
    {
    	[DataMember]
        public System.Guid Id { get; set; }
    	[DataMember]
        public System.Guid ConsumerId { get; set; }
    	[DataMember]
        public string Value { get; set; }
    	[DataMember]
        public bool Available { get; set; }
    	[DataMember]
        public System.DateTime EntryDate { get; set; }
    	[DataMember]
        public int TypeNo { get; set; }
    
    	[DataMember]
        public virtual ConsumerPropertyType ConsumerPropertyType { get; set; }
    	[DataMember]
        public virtual Consumer Consumer { get; set; }
    }
}
