//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivoosVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.AssetCommands = new HashSet<AssetCommand>();
            this.AssetDefaults = new HashSet<AssetDefault>();
            this.Safes = new HashSet<Safe>();
            this.Sessions = new HashSet<Session>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid GroupId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Available { get; set; }
        public string Url { get; set; }
        public string Exe { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public System.Guid UpdateStamp { get; set; }
        public string EnName { get; set; }
        public string EnDescription { get; set; }
        public string ArabicName { get; set; }
        public string ArabicDescription { get; set; }
        public string FrName { get; set; }
        public string FrDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetCommand> AssetCommands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetDefault> AssetDefaults { get; set; }
        public virtual AssetThumbnail AssetThumbnail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Safe> Safes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
