//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivoosVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public System.Guid Id { get; set; }
        public System.Guid PatientId { get; set; }
        public string Subject { get; set; }
        public string SymptomDescription { get; set; }
        public string SymptomType { get; set; }
        public Nullable<System.DateTime> SymptomStartDate { get; set; }
        public string SymptomResults { get; set; }
        public Nullable<int> IGDPoints { get; set; }
        public string Avoidance { get; set; }
        public string Precaution { get; set; }
        public string History { get; set; }
        public string PlaceOfFullSecure { get; set; }
        public string PlaceOfSecure { get; set; }
        public string PlaceOfHesitant { get; set; }
        public string PlaceOfUnsecure { get; set; }
        public string PlaceOfFullUnsecure { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
